### ISSUE TITLE
Use Foodcritic for static code analysis

### ISSUE THREAD

**Issue by leonardofl** [PoliGNU/sitedeploy#19]
Foodcritic is a helpful lint tool you can use to check your Chef cookbooks for common problems. 

It means... a kind of Sonar.

**Comment by diraol** [comment]
Foodcritic (and others) Added on 746141d16c10329afcd1e0baaf3e250159750531
Now, to run the kitchen tests and also the 'lint tools', we must use "rake <command>" (``rake default`` runs all possible tests, starting by the linters).

Run ``rake -T`` to see the options.

@leonardofl It is enough to close the issue? (I'm also adding codeclimate checks)

**Comment by leonardofl** [comment]
Great! A lot of changes and a big rakefile! :)
I have not run it yet, but it seems the issue is solved!
If I find any problem later I can open a more specific issue (assuming you are already running foodcritic, what seems to be true).

**Comment by diraol** [comment]
Yes, I have already tested it. :)
