### ISSUE TITLE
Smoke test

### ISSUE THREAD

**Issue by leonardofl** [PoliGNU/sitedeploy#20]
Include in the test suite a smoke test: something like verifing if `curl https://localhost:8443` contains the "PoliGNU" string.

**Comment by leonardofl** [comment]
@krlsdu @alfakini Any idea about the best way to do this?

**Comment by diraol** [comment]
Option 1:

https://blog.yimingliu.com/2008/02/04/testing-https-with-openssl/

https://www.feistyduck.com/library/openssl-cookbook/online/ch-testing-with-openssl.html

But I think we should aim to use http/2 protocolo.

Another thing is that we will use letsencrypt to get a valid SSL
certificate, so, may be we would first do the letsencrypt implementation
prior to these chekings here.

**Comment by leonardofl** [comment]
Ah, one special requirement: I would like to include the smoke test on the "kitchen test" execution rather than running a sepatated command.

**Comment by leonardofl** [comment]
PS: I believe implementing the test before having http2 or letsencrypt is valuable, since probably the test itself is easy to write: the harder will be how to fit it in our workflow.

**Comment by leonardofl** [comment]
Ah, maybe that rakefile thing will help!
I'll check it.

**Comment by leonardofl** [comment]
Implementing the smoke test:
ec035ee874fcbd189401c0967ac7fa8e90755538

To run it: `bats test/smoke`.

TODO:  put it on the rakefile.

**Comment by leonardofl** [comment]
It's necessary to install bats before... I will document it on the README.
