### ISSUE TITLE
Clean Rakefile

### ISSUE THREAD

**Issue by leonardofl** [PoliGNU/sitedeploy#23]
Remove from Rakefile things we do not need:

* Yard (documentation generation).
* ChefSpec (why I think it's unecessary: https://groups.google.com/forum/#!topic/tdd-no-mundo-real/fAvgIPs6DI0)
* Integration with cloud and docker (I believe testing with vagrant is just fine).

Less things on Rake, less confusion and more useful it will be.

If you agree, I prune this things by myself.

**Comment by diraol** [comment]
That is Ok for me =)
