### ISSUE TITLE
setup http port (80) 301 redirect to https (443)

### ISSUE THREAD

**Issue by diraol** [PoliGNU/sitedeploy#5]

**Comment by leonardofl** [comment]
The most important part is done: 21b5b260843ccf8ab922b032f7c4e9e9ccdc117f
But some adjusts are still necessary for remove hardcoded values on the recipe.

**Comment by leonardofl** [comment]
Adjusts done: 25a1fe3ada183043dbebd84ee2a3d5f86662a66d
